gui:
  language: 'en'
  showBottomLine: false

os:
  openCommand: 'open -a /Applications/Sublime\ Text.app "{{filename}}"'

customCommands:
  - key: 'F'
    command: 'git fetch --all'
    context: 'files'
    description: 'fetch all remote repos'
