gui:
  theme:
    activeBorderColor:
      - default
      - bold
    inactiveBorderColor:
      - '#2c2e34'
    selectedLineBgColor:
      - '#313542'
    selectedRangeBgColor:
      - '#313542'
  language: 'en'
  showBottomLine: false

os:
  openCommand: 'open -a /Applications/Sublime\ Text.app "{{filename}}"'

customCommands:
  - key: 'F'
    command: 'git fetch --all'
    context: 'files'
    description: 'fetch all remote repos'

  - key: 'F'
    command: 'git fetch --all'
    context: 'localBranches'
    description: 'fetch all remote repos'

  - key: 'F'
    command: 'git fetch --all'
    context: 'remotes'
    description: 'fetch all remote repos'

  - key: 'F'
    command: 'git fetch --all'
    context: 'remoteBranches'
    description: 'fetch all remote repos'

  - key: 'F'
    command: 'git fetch --all'
    context: 'commits'
    description: 'fetch all remote repos'

  - key: 'F'
    command: 'git fetch --all'
    context: 'tags'
    description: 'fetch all remote repos'
