"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "lowking"
email = "life@lowking.pro"

[ui]
editor = "vim"
default-command = ["log", "-r", ".."]

[signing]
behavior = "own"
backend = "gpg"

[snapshot]
auto-track = "none()"
