"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "lowking"
email = "life@lowking.pro"

[ui]
editor = "vim"
#merge-editor = "idea"
default-command = ["log", "-r", ".."]

[merge-tools.idea]
program = "/Applications/IntelliJ IDEA 2.app/Contents/MacOS/idea"
merge-args = ["merge", "$left", "$right", "$base", "$output"]

[signing]
behavior = "own"
backend = "gpg"

[snapshot]
#auto-track = "none()"

[git]
private-commits = "description(glob:'wip:*') | description(glob:'private:*')"

